name: Deploy Doxygen Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "include/**"
      - "src/**"
      - ".github/workflows/**"
      - "README.md"
      - "Doxyfile"
  pull_request:
    branches:
      - main
    paths:
      - "include/**"
      - "src/**"
      - ".github/workflows/**"
      - "README.md"
      - "Doxyfile"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install -y doxygen graphviz

      - name: Clone Doxygen Awesome CSS
        run: git clone https://github.com/jothepro/doxygen-awesome-css.git doxygen-awesome-css

      - name: Run Doxygen to generate docs
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
